### ISSUE TITLE
Some subrecord arrays should be subrecords with array fields.

### ISSUE THREAD

**Issue by WrinklyNinja** [TES5Edit/fopdoc#19]
This came up in #18, when I wrote the docs I misread `wbArray(ATTR, 'Attributes', wbInteger('Attribute', itU8), ...)` as meaning an array of ATTR subrecords, that get put under the UI heading "Attributes", each containing a byte-length attribute field, whereas it should be a single ATTR subrecord containing an array of byte-length attribute fields.

I will have made the same mistake in other places too, so they should be corrected.

**Comment by zilav** [comment]
Array of subrecords will look like `wbRArrayS('FormIDs', wbFormID(LNAM, 'FormID'), ...)`
Check forms list FLST record definition as an example.
